spring:
  application:
    name: forumrelatos
  datasource:
    url: jdbc:postgresql://localhost:5432/Serpro_test
    username: postgres
    password: 1122
    driver-class-name: org.postgresql.Driver
